/**
 * Goods Attributes Module Service
 * 
 * Manages Goods-specific product attributes.
 */

import { SwitchyardService } from "@switchyard/framework/utils"
import { ProductAttributes } from "./models/product-attributes"

class GoodsAttributesModuleService extends SwitchyardService({
  ProductAttributes,
}) {
  /**
   * Get all organic products
   */
  async getOrganicProducts(options?: { limit?: number; offset?: number }) {
    return this.listProductAttributes(
      { is_organic: true },
      { take: options?.limit || 100, skip: options?.offset || 0 }
    )
  }

  /**
   * Get products by brand
   */
  async getProductsByBrand(brand: string, options?: { limit?: number; offset?: number }) {
    return this.listProductAttributes(
      { brand },
      { take: options?.limit || 100, skip: options?.offset || 0 }
    )
  }

  /**
   * Get all products currently on ad/sale
   */
  async getProductsOnAd(options?: { limit?: number; offset?: number }) {
    return this.listProductAttributes(
      { on_ad: true },
      { take: options?.limit || 100, skip: options?.offset || 0 }
    )
  }

  /**
   * Get products matching dietary preferences
   */
  async getProductsByDietaryFlags(flags: {
    organic?: boolean
    gluten_free?: boolean
    vegan?: boolean
    non_gmo?: boolean
  }, options?: { limit?: number; offset?: number }) {
    const filters: Record<string, boolean> = {}
    if (flags.organic) filters.is_organic = true
    if (flags.gluten_free) filters.is_gluten_free = true
    if (flags.vegan) filters.is_vegan = true
    if (flags.non_gmo) filters.is_non_gmo = true

    return this.listProductAttributes(
      filters,
      { take: options?.limit || 100, skip: options?.offset || 0 }
    )
  }

  /**
   * Get unique brands
   */
  async getUniqueBrands() {
    // This would typically use a custom query
    // For now, list all and dedupe
    const all = await this.listProductAttributes({}, { take: 10000 })
    const brands = new Set(all.map(a => a.brand).filter(Boolean))
    return Array.from(brands).sort()
  }

  /**
   * Format warehouse location string from attributes
   * Returns format: "3C-2" (aisle + shelf_group + "-" + shelf)
   */
  formatWarehouseLocation(attributes: {
    inventory_type?: string | null
    warehouse_aisle?: string | null
    warehouse_shelf_group?: string | null
    warehouse_shelf?: string | null
  }): string | null {
    if (!attributes || attributes.inventory_type !== "Warehouse") {
      return null
    }

    const { warehouse_aisle, warehouse_shelf_group, warehouse_shelf } = attributes

    if (!warehouse_aisle || !warehouse_shelf_group || !warehouse_shelf) {
      return null
    }

    return `${warehouse_aisle}${warehouse_shelf_group}-${warehouse_shelf}`
  }

  /**
   * Validate inventory type value
   */
  validateInventoryType(type: string | null): boolean {
    if (!type) return true // null is valid (optional field)
    return ["Warehouse", "Sweep"].includes(type)
  }

  // retrieveProductAttributes and updateProductAttributes are auto-generated by SwitchyardService
}

export default GoodsAttributesModuleService

